#!/usr/bin/env bash

brew cask install \
  1password \
  adobe-acrobat-reader \
  firefox \
  firefox-developer-edition \
  google-chrome \
  istat-menus \
  iterm2 \
  nextcloud \
  slack \
  spectacle \
  spotify \
  visual-studio-code \
  goland \
  whatsapp \
  discord \
  joplin \
  zoomus
