#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew cask install \
  1password \
  adobe-acrobat-reader \
  firefox \
  firefox-developer-edition \
  google-chrome \
  istat-menus \
  iterm2 \
  nextcloud \
  slack \
  spectacle \
  spotify \
  visual-studio-code \
  goland \
  whatsapp \
  discord \
  joplin \
  zoomus
