---
- hosts: localhost
  vars:
    homebrew_installed_packages:
      - git
    
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - homebrew/php
      - homebrew/dupes
      - homebrew/versions
      - homebrew/homebrew-php
    
    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - 1password
      - adobe-acrobat-reader
      - cleanmymac
      - dropbox
      - firefox
      - flux
      - google-chrome
      - istat-menus
      - iterm2
      - nextcloud
      - skype
      - slack
      - spectacle
      - spotify
      - virtualbox
      - visual-studio-code
      - vlc
      - whatsapp

  roles:
    - role: geerlingguy.homebrew
...
